spring:
  main:
    banner-mode: off
  redis:
     host: "localhost"
     port: 6379
     timeout: 60000
  data:
    mongodb:
      host: "localhost"
      database: "caveservice"
      port:  27017
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration, org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
server:
  error:
    include-message: always
  port: 8080
debug: false
storage:
  #room: redisStorage
  room: mongoStorage
  #room: memoryStorage

