spring:
  main:
    banner-mode: off
  redis:
     host: "localhost"
     port: 6379
     timeout: 60000
  data:
    mongodb:
      host: "localhost"
      database: "caveservice"
      port:  27017
management:
  health:
    redis:
      enabled: false
    mongo:
      enabled: false
  endpoint:
    health:
      show-details: always
      show-components: always

    # Shutdown endpoint configuration
    shutdown:
      enabled: false

  # Actuator endpoint configuration
  endpoints:
    web:
      exposure:
        include: 'health, info'
server:
  error:
    include-message: always
  port: 8080
debug: false
storage:
  #room: redisStorage
  room: redisStorage
  #room: memoryStorage

