spring:
  main:
    banner-mode: off
  redis:
     host: "localhost"
     port: 6379
     timeout: 60000
  data:
    mongodb:
      host: "localhost"
      database: "caveservice"
      port:  27017
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration, org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
management:
  health:
    redis:
      enabled: false
    mongo:
      enabled: false
  endpoint:
    health:
      show-details: always
      show-components: never

    # Shutdown endpoint configuration
    shutdown:
      enabled: false

  # Actuator endpoint configuration
  endpoints:
    web:
      exposure:
        include: 'health'
server:
  error:
    include-message: always
  port: 8080
#  ssl:
#    key-store: classpath:${KEYSTORE:keystore.p12}
#    key-store-password: Maskot99
#    keyStoreType: PKCS12
#    keyAlias: caveservice
debug: false
storage:
  #room: redisStorage
  #room: redisStorage
  room: memoryStorage

